### ISSUE TITLE
AttributeError: 'list' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by vespersland** [R3gm/SoniTranslate#11]
After install dependencies on win 10 i got this error

AttributeError: 'list' object has no attribute 'endswith'
Traceback (most recent call last):
  File "C:\SoniTranslate\soni\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\SoniTranslate\soni\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\SoniTranslate\soni\lib\site-packages\gradio\blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\SoniTranslate\soni\lib\site-packages\gradio\blocks.py", line 1447, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\SoniTranslate\soni\lib\site-packages\gradio\components\file.py", line 247, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\SoniTranslate\soni\lib\site-packages\gradio\components\base.py", line 233, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\SoniTranslate\soni\lib\site-packages\gradio\components\base.py", line 197, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sub_ori.[]'

**Comment by vespersland** [comment]
> I’m translating the words of the developer, they were also about lemmas with launching on Windows
> 
> "Hello @Denskl1 , the program is not designed to run on Windows at the moment, but the error could be related to ffmpeg not being found in the system, so it needs to be installed; ffmpeg is a multimedia framework and you can install it on Windows by following this tutorial."

Same error now happen also on google colab

**Comment by R3gm** [comment]
Hello @vespersland, I have run the notebook and it works.

It could be a specific error. Could you send me the configurations you used to reproduce the error?

**Comment by zsofts** [comment]
This also happened a couple of times and in my opinion when it happens will: O SPEAKER DETECT IN SEGMENT: TTS auxiliary will be used in the segment time.

**Comment by vespersland** [comment]
> Hello @vespersland, I have run the notebook and it works.
> 
> It could be a specific error. Could you send me the configurations you used to reproduce the error?

I have tried all the settings but it continues to give me the usual error, even activating the 10 second preview function. 

Align complete
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/content/SoniTranslate/app_rvc.py", line 533, in translate_from_video
    diarize_model = whisperx.DiarizationPipeline(use_auth_token=YOUR_HF_TOKEN, device=device)
  File "/usr/local/lib/python3.10/dist-packages/whisperx/diarize.py", line 18, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
AttributeError: 'NoneType' object has no attribute 'to'

**Comment by zsofts** [comment]
Have you entered your personal token?

**Comment by zsofts** [comment]
I don't know, I didn't have any problems with it, and it definitely works on nvidia
