### ISSUE TITLE
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation

### ISSUE THREAD

**Issue by deinega** [R3gm/SoniTranslate#114]
Can we specify --compute_type?

Getting 

```
Traceback (most recent call last):
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "/home/a/code/SoniTranslate/app_rvc.py", line 365, in batch_multilingual_media_conversion
    output_file = self.multilingual_media_conversion(
  File "/home/a/code/SoniTranslate/app_rvc.py", line 708, in multilingual_media_conversion
    audio, self.result = transcribe_speech(
  File "/home/a/code/SoniTranslate/soni_translate/speech_segmentation.py", line 231, in transcribe_speech
    model = whisperx.load_model(
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/whisperx/asr.py", line 291, in load_model
    model = model or WhisperModel(whisper_arch,
  File "/home/a/miniconda3/envs/sonitr/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 131, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

```

**Comment by alexejtka4** [comment]
`python app_rvc.py --cpu_mode`

I overcame this error this way. I added the necessary flag to the launch command line

**Comment by deinega** [comment]
> I overcame this error this way. I added the necessary flag to the launch command line

But then GPU is not used, and it is very slow
