### ISSUE TITLE
i cant use it on ubuntu 24 and python 3.10

### ISSUE THREAD

**Issue by namdroid** [R3gm/SoniTranslate#135]
I get this error:

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.19.2, however version 4.44.1 is available, please upgrade.
--------
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/contextlib.py", line 153, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/route_utils.py", line 632, in dispatch
    |     response = await call_next(request)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    |     solved_result = await solve_dependencies(
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 666, in solve_dependencies
    |     ) = await request_body_to_args(  # body_params checked above
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 891, in request_body_to_args
    |     fields_to_extract = get_cached_model_fields(first_field.type_)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/_compat.py", line 659, in get_cached_model_fields
    |     return get_model_fields(model)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/_compat.py", line 285, in get_model_fields
    |     return [
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/_compat.py", line 286, in <listcomp>
    |     ModelField(field_info=field_info, name=name)
    |   File "<string>", line 6, in __init__
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/fastapi/_compat.py", line 111, in __post_init__
    |     self._type_adapter: TypeAdapter[Any] = TypeAdapter(
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/type_adapter.py", line 228, in __init__
    |     self._init_core_attrs(
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/type_adapter.py", line 290, in _init_core_attrs
    |     core_schema = schema_generator.generate_schema(self._type)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 610, in generate_schema
    |     schema = self._generate_schema_inner(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 863, in _generate_schema_inner
    |     return self._annotated_schema(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1977, in _annotated_schema
    |     schema = self._apply_annotations(source_type, annotations)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2056, in _apply_annotations
    |     schema = get_inner_schema(source_type)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    |     schema = self._handler(source_type)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2131, in new_handler
    |     schema = metadata_get_schema(source, get_inner_schema)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2127, in <lambda>
    |     lambda source, handler: handler(source)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    |     schema = self._handler(source_type)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2037, in inner_handler
    |     schema = self._generate_schema_inner(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 884, in _generate_schema_inner
    |     return self.match_type(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 986, in match_type
    |     return self._match_generic_type(obj, origin)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1014, in _match_generic_type
    |     return self._union_schema(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1325, in _union_schema
    |     choices.append(self.generate_schema(arg))
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 610, in generate_schema
    |     schema = self._generate_schema_inner(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 884, in _generate_schema_inner
    |     return self.match_type(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 995, in match_type
    |     return self._unknown_type_schema(obj)
    |   File "/home/pinguin/anaconda3/envs/py310/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 513, in _unknown_type_schema
    |     raise PydanticSchemaGenerationError(
    | pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
    | 
    | If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
    | 
    | For further information visit https://errors.pydantic.dev/2.10/u/schema-for-unknown-type

**Comment by namdroid** [comment]
pip install --upgrade pydantic==2.8.2
    pip install --upgrade pydantic-core==2.20.1
    pip install --upgrade fastapi==0.112.4

works
