### ISSUE TITLE
app_rvc.py

### ISSUE THREAD

**Issue by mohitpal2621** [R3gm/SoniTranslate#14]
When running python app_rvc.py, how do I resolve this?
`/tmp/gradio/6cb4020ad75bb1cb116c865ab91842f8753c7acc/Video_main.mp4
Process video...
process audio...
process audio...
...
Error can't create the audio file
Traceback (most recent call last):
  File "/home/mohit/Projects/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/mohit/Projects/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/mohit/Projects/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/mohit/Projects/venv/lib/python3.10/site-packages/gradio/components/file.py", line 254, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/home/mohit/Projects/venv/lib/python3.10/site-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/home/mohit/Projects/venv/lib/python3.10/site-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sub_ori.srt'`

**Comment by R3gm** [comment]
Hello, sorry for responding late. In Linux, you need to install ffmpeg, which might be causing the issue

**Comment by cosanostratr** [comment]
up
