### ISSUE TITLE
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match

### ISSUE THREAD

**Issue by serjik777** [R3gm/SoniTranslate#22]
[INFO] >> Cache flushed
[INFO] >> Processing video...
[INFO] >> Process video...
[INFO] >> Process audio...
[INFO] >> Transcribing...
Traceback (most recent call last):
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\gradio\route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\gradio\blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\gradio\blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\gradio\utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "C:\SoniTranslate\app_rvc.py", line 436, in multilingual_media_conversion
    audio, self.result = transcribe_speech(
  File "C:\SoniTranslate\soni_translate\speech_segmentation.py", line 34, in transcribe_speech
    model = whisperx.load_model(
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\whisperx\asr.py", line 347, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
  File "C:\Users\ded\bin\miniconda\envs\venvst\lib\site-packages\whisperx\vad.py", line 47, in load_vad_model
    raise RuntimeError(
_RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.
How to solve this problem_

**Comment by gellote** [comment]
I had the same problem but the console gave me an error in the whisperx-vad-segmentation.bin file and my solution was to delete this file and run sonitranslate again so that it downloads again.
The file path is in C:\Users\your user\.cache\torch

**Comment by R3gm** [comment]
You need to remove the whisperx-vad-segmentation.bin file, and there's some additional information about this in [whisperX#389](https://github.com/m-bain/whisperX/issues/389)
