### ISSUE TITLE
Issues with diarization and pyannote 3.1

### ISSUE THREAD

**Issue by Ibrahima-prog** [R3gm/SoniTranslate#29]
Hey, truly incredible, thank you for all your efforts, 

i am having an issue with pyannote 3.1 on Google Collab (pyannote 2.0 works fine)

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "/content/SoniTranslate/app_rvc.py", line 288, in batch_multilingual_media_conversion
    output_file = self.multilingual_media_conversion(
  File "/content/SoniTranslate/app_rvc.py", line 549, in multilingual_media_conversion
    self.result_diarize = diarize_speech(
  File "/content/SoniTranslate/soni_translate/speech_segmentation.py", line 175, in diarize_speech
    raise error
TypeError: exceptions must derive from BaseException

**Comment by R3gm** [comment]
Hi,
You've got access to the Piannote_3 models? Here are the links: https://huggingface.co/pyannote/speaker-diarization-3.1/tree/main and https://huggingface.co/pyannote/segmentation-3.0/tree/main

**Comment by Ibrahima-prog** [comment]
Thank you very much, i had access to the first one and not the latter.
