### ISSUE TITLE
Issue installing Piper TTS  and Coqui XTTS

### ISSUE THREAD

**Issue by Doris1337** [R3gm/SoniTranslate#37]
So I don't know much about coding but this is the last steps what appeared:

DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: onnxruntime-gpu
Successfully installed onnxruntime-gpu-1.17.1

(sonitr) A:\Art_intel\SoniTranslate>pip install -q piper-tts==1.2.0
ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.1.0 (from piper-tts) (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.1.0

(sonitr) A:\Art_intel\SoniTranslate>pip install -q -r requirements_xtts.txt
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyannote-audio 3.1.1 requires omegaconf<3.0,>=2.1, but you have omegaconf 2.0.6 which is incompatible.
pyannote-database 5.1.0 requires typer>=0.12.1, but you have typer 0.9.4 which is incompatible.

**Comment by Doris1337** [comment]
And when trying  I get this error: 

Traceback (most recent call last):
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\gradio\route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\gradio\blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\gradio\blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\gradio\utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "A:\Art_intel\SoniTranslate\app_rvc.py", line 288, in batch_multilingual_media_conversion
    output_file = self.multilingual_media_conversion(
  File "A:\Art_intel\SoniTranslate\app_rvc.py", line 497, in multilingual_media_conversion
    audio, self.result = transcribe_speech(
  File "A:\Art_intel\SoniTranslate\soni_translate\speech_segmentation.py", line 34, in transcribe_speech
    model = whisperx.load_model(
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\whisperx\asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
  File "C:\Users\Player1\miniconda3\envs\sonitr\lib\site-packages\faster_whisper\transcribe.py", line 131, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

**Comment by R3gm** [comment]
Try changing the compute type in "Advanced Settings." You will see an option for "Compute type"; change it to int8 or float32. Internally, Faster Whisper is used, and the problem may be from there. [similar error](https://github.com/SYSTRAN/faster-whisper/issues/42)
The `piper-phonemize` module is not officially supported on Windows, hence the error. I created an experimental version that can be installed, but it's not very stable. Here's a future guide for installation: [link](https://github.com/R3gm/SoniTranslate/blob/dev_24_3/docs/windows_install.md)

**Comment by Doris1337** [comment]
thanks, works as charm! by the way awesome job with the app
