### ISSUE TITLE
ModuleNotFoundError: No module named 'rarfile'

### ISSUE THREAD

**Issue by LearnAI-gold** [R3gm/SoniTranslate#78]
Hi,

Thank you for sharing the project detail. I followed your instruction on Window 11 using anaconda prompt. While running below command,I am getting error. Can you please suggest solution.

(sonitr) C:\Windows\System32\SoniTranslate>python app_rvc.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "C:\Windows\System32\SoniTranslate\app_rvc.py", line 10, in <module>
    from soni_translate.audio_segments import create_translated_audio
  File "C:\Windows\System32\SoniTranslate\soni_translate\audio_segments.py", line 3, in <module>
    from .utils import run_command
  File "C:\Windows\System32\SoniTranslate\soni_translate\utils.py", line 1, in <module>
    import os, zipfile, rarfile, shutil, subprocess, shlex, sys # noqa
ModuleNotFoundError: No module named 'rarfile'

**Comment by LearnAI-gold** [comment]
Fixed with Pip install command, 

pip install rarfile

**Comment by eliasribeiro** [comment]
I had the same message, these were the steps to resolve it:

pip install rarfile
pip install srt
pip install ffmpeg
pip install faiss-cpu
pip install --upgrade pyannote.audio
conda install -c conda-forge parselmouth
pip install praat-parselmouth
pip install pyworld faiss-cpu librosa torchcrepe

I did trial and error, until I finally managed to run SoniTranslate after all these commands.
