### ISSUE TITLE
Youtube: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by hecho83** [R3gm/SoniTranslate#87]
Hello,

I have the last version of SoniTranslate (2024/05/18) running on my computer under ubuntu, but the problem persist in personal google colab and in SoniTranslate demo.

Many months ago I used SoniTranslate with success!

The issue regard only youtube video. When I insert the youtube URL and click on "Translate", I receive the erro "ERROR". In the console I have the errors:

```
Traceback (most recent call last):
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/luca/miniconda3/envs/sonitr/lib/python3.10/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "/home/luca/SoniTranslate/app_rvc.py", line 365, in batch_multilingual_media_conversion
    output_file = self.multilingual_media_conversion(
  File "/home/luca/SoniTranslate/app_rvc.py", line 621, in multilingual_media_conversion
    audio_video_preprocessor(
  File "/home/luca/SoniTranslate/soni_translate/preprocessor.py", line 194, in audio_video_preprocessor
    raise OperationFailedError(f"Error can't download the video:\n{errors.decode('utf-8')}")
soni_translate.preprocessor.OperationFailedError: Error can't download the video:
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

Has anyone had the same problem and knows how it could be solved?

Thanks
Luca

**Comment by hecho83** [comment]
resolved upgrading yt-dlp:

pip install --upgrade yt-dlp

**Comment by Ibrahima-prog** [comment]
This (new version of yt-dlp) should be added to a new version of this repo.
